### ISSUE TITLE
Curl failed with code 7 (Couldn't connect to server)

### ISSUE THREAD

**Issue by gmarkan** [usnistgov/ACVP-Server#134]
**environment**
The environment the issue was experienced Demo

**testSessionId**
The test session ID

**vsId**

**Algorithm registration**
app/acvp_app --aes --verbose

**Endpoint in which the error is experienced**
app/acvp_app --aes --verbose

Using the following parameters:

    ACV_SERVER:     127.0.0.1
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/

Warning: No server set, using default. Please define ACV_SERVER in your environment.
Run acvp_app --help for more information on this and other environment variables.

***ACVP [STATUS][acvp_login:2509]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:483]--> HTTP User-Agent: libacvp/1.0;Linux;4.4.0-210-generic;x86_64;Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz;GCC/5.3.1

***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 7 (Couldn't connect to server)

***ACVP [INFO][log_network_status:1464]--> POST Login...
        Status: 0
        Url: https://127.0.0.1:443/acvp/v1/login
        Resp: Recieved

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2521]--> Login Send Failed
***ACVP [ERR][acvp_run:3200]--> Failed to login with ACVP server

**Expected behavior**
Login successful

**Additional context**
Can you please help

**Comment by Kritner** [comment]
@gmarkan it sounds like you're describing an issue with the client you're attempting to use, not the actual ACVP service - you might be better off reading the documentation or opening an issue with the client repository [libacvp](https://github.com/cisco/libacvp/)

However from the error message above, it states you haven't set an ACV_SERVER environment variable, and your curl command is pointing to the loopback address, rather than our server address, I assume, because of the lack of the previously mentioned variable.

**Comment by gmarkan** [comment]
Hello,

For some reason when I run ./nist_setup.sh,  ACV_SERVER environment variable was not getting set. However when I ran source nist_setup.sh, was able to get past this issue and login successfully.

**Comment by jarnold01** [comment]
hi @gmarkan, yes, using the source command allows for the environment variables defined in the nist_setup.sh script to be loaded into the current running shell (instead of simply executing the script, which would set the variables in a subshell, and would immediately close following the script's completion).
