### ISSUE TITLE
KAS 56C KDF OneStep: FixedInput requirements are unclear

### ISSUE THREAD

**Issue by swkeypair** [usnistgov/ACVP-Server#15]
**Given the following test target:**
- The associated KAS scheme is C(2e, 0s), no key confirmation.
- algorithm: KAS-KDF
- mode: OneStep
- revision: Sp800-56Cr1
- auxFunctionName: SHA2-256

**And** given that ACVP testing requires _FixedInput_ and fields within _FixedInput_ (although these are not mandated by 56Ar3 and 56Cr2);

 The specification of _uPartyInfo_ and _vPartyInfo_ are not precise about what is optional and what is required for the current ACVP test process. Using uPartyInfo as the example, it is specified as:

> uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
> - "optional" items **such as** ephemeralKey MUST be included when available for ACVP testing.

Which of these optional fields must be included for the ACVP system to accept the registration?
Just _ephemeralKey_?
All of them? 
What is _c_ in this specification? It does not appear to be described in the 56Ar3 and 56Cr2 sections cited next.

References to _FixedInfo_ in source specifications:
[SP 800-56C Section 4.1 Input item c. _FixedInfo_](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf#page=21) refers the reader to SP 800-56Ar3. 
[SP 800-56Ar3 Section 5.8.2.1.1 ](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf#page=66)provides some help:

> PartyUInfo: A required non-null subfield containing public information about party U.
At a minimum, _PartyUInfo_ shall include IDU, an identifier for party U, as a distinct item of information. This subfield could also include information about the public key(s) contributed to the key-agreement transaction by party U. The nonce provided by party U as required in a **C(0e, 2s)** scheme (see Section 6.3) shall be included in this subfield.

The ACVP specification cites both ephemeralNonce and dkmNonce, while the 56r3 specification cites the nonce provided by party U in a static scheme (not the one used in this case).

Can you provide a working registration example for the Hash option case?

Final observation / question: given that this testing is new, should the ACVP test coverage (and therefore "revision" field) cite
SP800-56Cr2 rather than SP 800-56r1?

Thank you

**Comment by Kritner** [comment]
> And given that ACVP testing requires FixedInput and fields within FixedInput (although these are not mandated by 56Ar3 and 56Cr2);

> The specification of uPartyInfo and vPartyInfo are not precise about what is optional and what is required for the current ACVP test process. Using uPartyInfo as the example, it is specified as:

A lot of [this issue](https://github.com/usnistgov/ACVP/issues/1023) I believe covers some of the question being posed above.  But the tldr is:

* using `uPartyInfo` as an example (but it also applies to vPartyInfo)
* specifying `uPartyInfo` as a portion of the `fixedInfoPattern` (which is *required*, the positioning of it in the pattern is where variation can occur)
* `uPartyInfo` is comprised of the concatenation of "1 to 2" pieces of data, depending on the scheme.
  * The "1" that is always a part of the `uPartyInfo` is the "id" of the party (iutId or serverId)
  * the "2" is made up of `ephemeralKey`, `ephemeralNonce`, `dkmNonce`, or `c`, again depending on the scheme
    * not all schemes will have this second piece of data, it is completely dependent on the scheme and the party contributions based on that parties role in the scheme.

In the case of standalone KDF testing, we'll randomly provide ephemeral data or not in test cases, to ensure that the IUT is able to properly construct the `fixedInfo` for varying "schemes".  While "schemes" don't exist for the KDF testing specifically, this including (or not) of ephemeral data will ensure the IUT is able to properly construct the `fixedInfo`.

As an example:

```json
{
  "uPartyId": "1001",
  "vPartyId": "CAFE",
  "uPartyEphemeralData": "1010101010",
  "vPartyEphemeralData": null,
  "fixedInfoPattern": "uPartyInfo||vPartyInfo"
}
```

Given the above situation, both party u and party v would construct the fixed info for the above test case as:

```
10011010101010CAFE
```

which is the concatenation of "uPartyInfo", which is made up of "uPartyId||uPartyEphemeralData", then "vPartyInfo" which is made up of "vPartyId" (party V ephemeral data is not included in what makes up this party info as per the test case).

So breaking the above into its individual pieces, to hopefully visually explain the concatenation:

```
uPartyId||uPartyEphemeralData||vPartyId
1001||1010101010||CAFE
```

-----

> Which of these optional fields must be included for the ACVP system to accept the registration?

both `uPartyInfo` and `vPartyInfo` must be in the `fixedInfoPattern` within the registration, `uPartyInfo` and `vPartyInfo` are a (potentially) compound field made up of the party's ID, and ephemeral data depending on the scheme.

> What is c in this specification? It does not appear to be described in the 56Ar3 and 56Cr2 sections cited next.

`c` is relevant only to SP800-56Br2, it is the ciphertext that is produced/provided by one or both parties against their local `z` value.  It's not relevant to SP800-56Ar3 or SP800-56Cr1 directly, but for reuse purposes it was included in the fixed info pattern construction examples to (attempt) to make it clear that the `[x]PartyInfo` field is a compound field consisting of one or more pieces of data.

-----

> Can you provide a working registration example for the Hash option case?

I don't understand this question, can you elaborate? is this related to one step kdf?

```json
{
  "algorithm": "KAS-KDF",
  "mode": "OneStep",
  "revision": "Sp800-56Cr1",
  "isSample": true,
  "auxFunctions": [
    {
      "auxFunctionName": "SHA2-224"
    }
  ],
  "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
  "encoding": [
    "concatenation"
  ],
  "z": [
    {
      "min": 224,
      "max": 65336,
      "increment": 8
    }
  ],
  "l": 1024
}
```

-----

> Final observation / question: given that this testing is new, should the ACVP test coverage (and therefore "revision" field) cite
SP800-56Cr2 rather than SP 800-56r1?

I have not yet implemented changes to our testing that would have been introduced in SP800-56Cr2.  I don't think there were many, but I haven't had a close look.

**Comment by swkeypair** [comment]
> Can you provide a working registration example for the Hash option case?

Sorry I was imprecise - your response was what I was asking for, thank you.

> While "schemes" don't exist for the KDF testing specifically, this including (or not) of ephemeral data will ensure the IUT is able to properly construct the fixedInfo.

OK. But with this KDF testing handled as a separate item from the remainder of the KAS testing, how does this test even have information about the scheme? This seems out of the scope of the KDF test proper.

It seems like the KDF test can only treat FixedInfo as a field which should be present but whose value cannot be known.

**Comment by Kritner** [comment]
>> While "schemes" don't exist for the KDF testing specifically, this including (or not) of ephemeral data will ensure the IUT is able to properly construct the fixedInfo.

> OK. But with this KDF testing handled as a separate item from the remainder of the KAS testing, how does this test even have information about the scheme? This seems out of the scope of the KDF test proper.

> It seems like the KDF test can only treat FixedInfo as a field which should be present but whose value cannot be known.

Sorry I don't think I fully understand what is being asked.

Basically as you and I both said, "schemes" are separate from the standalone KDF testing.  The KDF testing can be used to be considered a "full kas" validation when it is paired with KAS-IFC-SSC, KAS-ECC-SSC, or KAS-FFC-SSC testing.  Because of the fact a specific scheme, and the per party generation requirements for each scheme (like generating/providing a key pair, nonce, etc) are not known, we cover the different situations of what is provided for varying schemes.  We're accomplishing this "party generation requirements covering" by testing in some cases where one or both parties have "ephemeral data" contributed to the fixed info, or not.

If you look at the sample prompt file here: https://usnistgov.github.io/ACVP/draft-hammett-acvp-kas-kdf-onestep.html#name-example-test-vectors-json you'll see that a "partyId" is always included in each test case, regardless of partyU or partyV.  However, the "ephemeralData" is included randomly for each test case, for each party.  The random inclusion or exclusion of the ephemeral data (as it relates to fixed info construction that gets plugged into the KDF), helps ensure that the KDF implementation can handle numerous schemes, without actually testing the SSC component or specific party generation requirements of any individual scheme.

Just to expand on an example from the prompt file linked above, the following test case:

```
{
	"tcId": 307,
	"kdfParameter": {
		"kdfType": "oneStep",
		"salt": "C81EE36994067D90AC11850A2E904B35",
		"z": "98AE8419CEDD3CBEABAC947E4AD281235586A16AD9463A638296A03962FCC0C99A24FDD2"
	},
	"fixedInfoPartyU": {
		"partyId": "C8292D3655488EEE69F52E4F74A98A6E",
		"ephemeralData": "DF507114129074574BEF5B698CF50611F8DF6AAD8CDE69C8C3FCA45114341BD92A50A5C8"
	},
	"fixedInfoPartyV": {
		"partyId": "C288C96A2526A5F889FD60756E946E5D"
	}
}
```

```json
"kdfConfiguration": {
        "kdfType": "oneStep",
        "saltMethod": "random",
        "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
        "fixedInfoEncoding": "concatenation",
        "auxFunction": "KMAC-128"
      }
```

would invoke the kdf as so:

```cs
var result = kdf(
  // z
  "98AE8419CEDD3CBEABAC947E4AD281235586A16AD9463A638296A03962FCC0C99A24FDD2", 
  // uPartyInfo||vPartyInfo||l
  // uPartyId||uEphemeralData||vPartyId||l
  // C8292D3655488EEE69F52E4F74A98A6E || DF507114129074574BEF5B698CF50611F8DF6AAD8CDE69C8C3FCA45114341BD92A50A5C8 || C288C96A2526A5F889FD60756E946E5D || 00000200
  "C8292D3655488EEE69F52E4F74A98A6EDF507114129074574BEF5B698CF50611F8DF6AAD8CDE69C8C3FCA45114341BD92A50A5C8C288C96A2526A5F889FD60756E946E5D00000200"
);
```
