### ISSUE TITLE
Why do PQGVer tests for G Generator Unverifiable per Section A.2.2 include parameters used only in A.2.3?

### ISSUE THREAD

**Issue by swkeypair** [usnistgov/ACVP-Server#188]
Why do PQGVer GGen unverifiable verification method request files include parameters that don't apply to the algorithm?

Specifically, FIPS 186-4 Section A.2.2 uses only p, q and g. This is confirmed in the corresponding [gen-val code])(https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/src/crypto/src/NIST.CVP.ACVTS.Libraries.Crypto/DSA.FFC/GGeneratorValidators/UnverifiableGeneratorGeneratorValidator.cs#L55-L72). The code does exactly what the A.2.2 process indicates and these other values are superfluous. 
Is there a purpose for these parameters in this test?

Here is an example snippet of a DSA pqgVer .REQ file with some of the extra parameters italicized (the choice of hash seems out of the scope of this test as well).
    {
         "tgId": 22,
         "testType": "GDT",
         "gMode": "unverifiable",
         "l": 1024,
         "n": 160,
         "hashAlg": "SHA2-224",
         "tests": [
            {
               "tcId": 106,
               "p": "B82C8DFB4F66EACE1FEA320E9A141D68D7F581E9178A67036FC36085854A408789AA2436E707269179CFF7A95FFC4E8BC45AB1F2CA7E9E7AE72301226770FEB2C53A7EFE67783B07BFBAE81D4640D4880480569EB8AB378D63E134AD468D7C564F81AC5271CA452AFE4AAD4108D94B138A01B3F0B48ED3193FB9594BE7EDBB07",
               "q": "907217EE8D52879A80E4D270864F74DA6C6560B7",
               "g": "A3FE6A8AE12CE94D30390C3E402321E9FC1ABEAD54FE0B46BBB42A360F946525524A8623BA1F4D909E1122FF21D0B240AA56B9B66573AEC0555930AD8B662A49DEE61DB8DD1FD244D814F353BC6BDB8D1A54D6DC285B6232C6DF3B9991F824906DE71431982F53926A9FB4DF0A29C2284E8D6C7D4043F5E6890D223BD156E219",
               _"h": "02",
               "domainSeed": "F9984B058E971FE393241A56423EB1D10322F207"_
            },

**Comment by celic** [comment]
Often we'll do this through the gen/vals. Sometimes properties that aren't needed are still generated with a random value to avoid cases where the generation code needs to know more about the crypto than it really should. 

The `internalProjection.json` files are a full serialization of our `TestVectorSet`, `TestGroup`, and `TestCase` structures, so they will include questions, answers, and sometimes a little extra we don't show a user normally. 

I think in this particular case, we need _something_ in order to generate a `p` and `q` to use during testing. Usually we will access the pools in this case to grab _anything_ that meets the criteria quickly, and it may mean grabbing extra information we don't normally use or need. 

See here: https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/src/generation/src/NIST.CVP.ACVTS.Libraries.Generation/DSA/v1_0/PqgVer/TestCaseGeneratorG.cs. We fill in some values with static elements so that we know a pool exists and is ready to go. These values just happen to get placed back into the structure to appear in the `internalProjection.json` it seems. 

For the hash function, it's an Enum and I don't think there is a `null` on it. It may be defaulting to the first value in the list, but that seems odd to be SHA2-224 instead of SHA-1. It seems coincidental it's using the same hash function used in the pool request in the file I linked above.
