### ISSUE TITLE
Question on implementation of RSA siggen/sigver using sha3

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#195]
Is there a planned schedule for when RSA signature tests will support SHA3?

**Comment by celic** [comment]
No schedule, but planned eventually. Some signature schemes define OIDs that are not defined for SHA-3. It is unclear what the expected behavior is as the OIDs are managed by a non-NIST organization. 

As well it is not clear in FIPS 202 how to hash an integer using SHA-3. You may know we use a little-endian format for hashing bits in SHA-3, and it is not clear how this applies to integer values that may be used in signatures. It seems selecting a way to understand the bit ordering of the integer would be arbitrary, but I suppose industry must do it somehow.

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.28](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.28).

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.28](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.28).
