### ISSUE TITLE
Deciphering "No modification" failure reason for RSA sigVer

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#201]
**environment**
Demo

**testSessionId**
240243

**vsId**
948590

Hello,

Playing with some harness code for RSA sigVer, and am failing 1-2 test cases per test group at random with the reason "No modification".

I was wondering if I could get some explanation as to what "no modification" means; it could also be helpful if that reason string was fleshed out a tiny bit.

VSID 948590 on testsession 240243 is one of the vector sets in question.

Thanks for any input!

Andrew

**Comment by livebe01** [comment]
Sure, it looks like you're returning "testPassed":false for all of the test cases in that vector set where the expectation is that some of the tests should pass. 

E.g., for tcId 5, the expected answer is "testPassed": true, whereas "testPassed": false is being submitted.

The test itself is whether the signature provided is valid for the accompanying message. The test, e.g., tcId 5, failed because the IUT indicated that the signature provided was not valid for the accompanying message whereas the signature provided should actually be valid for the message. I think the "no modification" is meant to get at the fact that we/ACVTS didn't modify the message/signature and so the test should pass vs fail. It'd make sense to update this message to something that's more meaningful to a tester vs us :). I'll label this as an "enhancement" vs "bug".

**Comment by abkarcher** [comment]
Hi,

Thanks for the info! Looks like I had inadvertently saved a bad code change between my sample run and my server tests. Whoops! Definitely don't want to be marking every single case as false.

Thanks for looking at the message change! Closing - 

Andrew

**Comment by livebe01** [comment]
The fix for this is now on Demo, v1.1.0.25.
