### ISSUE TITLE
Git index has at least one corrupt entry.  Windows machines can't clone this tree.

### ISSUE THREAD

**Issue by v-rackerman** [usnistgov/ACVP-Server#220]
Git index has at least one corrupt entry in it preventing a Windows machine from being able to clone this tree.

You can see it in the index at _offset 0x342c16_ --> `kgen-val/src/generation/test/NIST.CVP.ACVTS.Libraries.Generation.Core.Tests/bin/Debug/net5.0/C:\temp/DNA.log`

This produces the following error when attempting to clone on a Windows machine:
`error: invalid path 'gen-val/src/generation/test/NIST.CVP.ACVTS.Libraries.Generation.Core.Tests/bin/Debug/net5.0/C:\temp/DNA.log'`

**Cloning from Linux works** and creates a silly filename rather than barfing on the path.

**Comment by livebe01** [comment]
Hi @v-rackerman, can you verify that this remains an issue? I just pushed our latest release to this repository and I'm wondering if that will resolve the corruption you're experiencing. Thanks!

**Comment by v-rackerman** [comment]
I tested this just now.  

No, nothing is fixed.  "error: invalid path 'gen-val/src/generation/test/NIST.CVP.ACVTS.Libraries.Generation.Core.Tests/bin/Debug/net5.0/C:\temp/DNA.log'"

**Comment by Kritner** [comment]
this is likely due to dropping the repository folder in for upload.  That repository folder has artifacts in it that shouldn't really be a part of the github repo like bin, obj, etc.

For whatever reason in the method that the repository is being uploaded/mirrored here, the gitignore... is being ignored.

**Comment by livebe01** [comment]
You’ve got it Russ. Pretty sure I have it fixed, have just been running into a few issues getting it pushed back out to GitHub. I should be able to get past those issues by later today though...

Ben



On Sep 19, 2022, at 10:42 PM, Russ Hammett ***@***.******@***.***>> wrote:



this is likely due to dropping the repository folder in for upload. That repository folder has artifacts in it that shouldn't really be a part of the github repo like bin, obj, etc.

For whatever reason in the method that the repository is being uploaded/mirrored here, the gitignore... is being ignored.

**Comment by livebe01** [comment]
Hi @v-rackerman, the `gen-val/src/generation/test/NIST.CVP.ACVTS.Libraries.Generation.Core.Tests/bin/Debug/net5.0/C:\temp/DNA.log` issue should be gone now. Can you verify?

**Comment by v-rackerman** [comment]
fixed!  Thank you.
