### ISSUE TITLE
error message reported by ACVTS demo in verdict returned

### ISSUE THREAD

**Issue by rnunez83** [usnistgov/ACVP-Server#222]
**environment**
The environment the issue was experienced: Demo after posting response.json

**testSessionId**
The test session ID:
  - testID 273299

**vsId**
The vectorSet ID displaying the issue:
  - vsid 1084280, vsid 1084281, vsid 1084282

**Expected behavior**
  - Verdicts are expected to pass

**Additional context**
  - I have been processing a set of test vectors against the demo ACVTS and on 3 of my test results I see an odd verdict. I am not sure what the error means and was hoping you can provide some clarity.

vsid 1084280 returns the following verdict
"error": "Error setting value to \u0027ReasonName\u0027 on \u0027NIST.CVP.ACVTS.Libraries.Generation.RSA.v1_0.SigVer.TestCase\u0027."

vsid 1084281 returns the following verdict
"error": "Unexpected error parsing JSON enum of type NIST.CVP.ACVTS.Libraries.Crypto.Common.KAS.Enums.FixedInfoEncoding"

vsid 1084282 returns the following verdict
"error": "Unexpected error parsing JSON enum of type NIST.CVP.ACVTS.Libraries.Oracle.Abstractions.DispositionTypes.KasSscTestCaseExpectation"

**Comment by livebe01** [comment]
Hi @rnunez83,

The v1.1.0.25 release included the following changes that are effecting these vector sets:
* RSA sigVer - Updates the "reason" given when an IUT returns testPassed:false when testPassed:true is expected for RSA sigVer to give the tester some additional clarity. Changes reason from "No modification" to "No modification, i.e., "testPassed": true expected".
* KAS - Enforces case sensitivity for some registration parameters where enforcement of case sensitivity had been previously overlooked/not enforced

These changes introduced an "incompatibility" such that the demo server running v1.1.0.25 is unable to check the results for some vector sets (mostly RSA sigVer and KAS-related, but perhaps a few more) that were created using v1.1.0.24. 

The fix for these errors is to request these vector sets again. I do apologize as I realize that this is not convenient.

-Ben

**Comment by rnunez83** [comment]
Hi Ben,

Thanks for the quick reply and clear explanation to the problem. I will go ahead and request new vectors then. 

Follow-up question. I generated production vectors around the same time. Would these test vectors be affected as well (i.e., do I need to generate new production vectors)?

**Comment by livebe01** [comment]
Sure thing.

For your production vector sets - they won't be effected until v1.1.0.25 goes to prod. So if you can submit the answers on prod before the release gets there, you'll be good. I don't have a date for getting v1.1.0.25 to prod, perhaps late next week.

**Comment by GlennUL** [comment]
@livebe01 

I have a question regarding production vectors once the update is released to prod. If RSA sigVer was tested and passed but not yet submitted for validation will these passed vectors still be valid to certify or will it require retesting under v1.1.0.25?

**Comment by livebe01** [comment]
Hi Glenn, I believe that this issue only effects the "submission of results" process and does not effect the certify process. If the RSA sigVer was tested and passed, I don't believe there should be any issues w/ certifying.

**Comment by GlennUL** [comment]
Thanks for the confirmation Ben!

**Comment by livebe01** [comment]
We wanted to provide an update that we were able to create a fix for this issue. The fix was applied on 9/14/22 to Demo and this should not be an issue when the v1.1.0.25 release goes to Prod.

**Comment by rnunez83** [comment]
Thanks for the update. I'll go ahead and close this ticket.
