### ISSUE TITLE
GMAC RETRY30

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#24]
**environment**
Demo

**testSessionId**
118741

**vsId**
344099

After we submitted our result. The result of validation, expected result and vector sets are all become "retry": 30.

**Comment by celic** [comment]
We see all these files are available to be retrieved. Is this still the case?

**Comment by AndrewHYang** [comment]
Yes, I can get them now. But it took almost a day. Is that normal?

**Comment by celic** [comment]
It is odd, but we didn't see anything on the server indicating something bad happened. Sorry this happened, but we didn't learn any information about how the problem was produced in the first place. No errors, everything processed fine, data was in the right place. We will keep an eye out, but I think this can just be closed for now.
