### ISSUE TITLE
Unable to map RSA signaturePrimitive 2.0

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#245]
**environment**
Demo

**Algorithm registration**
{
    "algorithms": [
        {
            "algorithm": "RSA",
            "mode": "signaturePrimitive",
            "revision": "2.0",
            "keyFormat": [
                "standard"
            ],
            "pubExpMode": "random",
            "modulus": [
                2048,
                3072,
                4096
            ]
        }
    ],
    "encryptAtRest": false,
    "isSample": false
}

**Expected behavior**
Successful generation of vectors.

**Additional context**
When trying to create a test session for RSA signaturePrimitive 2.0 we receive the following error message: Unable to map RSA-signaturePrimitive-2.0 - index 0 to an internal algorithm id.

**Comment by livebe01** [comment]
Hi Glen, double check your “mode” value. That should get you where you want to be…

Ben



On Mar 10, 2023, at 5:07 PM, GlennUL ***@***.***> wrote:



environment
Demo

Algorithm registration
{
"algorithms": [
{
"algorithm": "RSA",
"mode": "signaturePrimitive",
"revision": "2.0",
"keyFormat": [
"standard"
],
"pubExpMode": "random",
"modulus": [
2048,
3072,
4096
]
}
],
"encryptAtRest": false,
"isSample": false
}

Expected behavior
Successful generation of vectors.

Additional context
When trying to create a test session for RSA signaturePrimitive 2.0 we receive the following error message: Unable to map RSA-signaturePrimitive-2.0 - index 0 to an internal algorithm id.

**Comment by GlennUL** [comment]
Hi Ben,

We must be missing something as our developers and myself don't see anything off with the "mode" value when we compare it to the documentation.

Thanks,
Glenn

**Comment by livebe01** [comment]
Ah, sorry Glenn. That was a mistake on my part. RSA signaturePrimitive 2.0 is an algorithm that we're working to add, but is one that we've yet to release to Demo. We should have waited to update our documentation until we'd released the algorithm to Demo. That said, I'm hesitant to back it out of our documentation as it pops up in lots of niggling places and the pain of making sure we've successfully removed it from all, then added it back in to all.

**Comment by GlennUL** [comment]
That makes sense. Thanks for the update!

**Comment by ehanson12** [comment]
Is RSA signaturePrimitive 2.0 released to production? For some reason this worked on DEMPO last week for a few days...
