### ISSUE TITLE
/health endpoint no longer returning a "status" value

### ISSUE THREAD

**Issue by mikeboulet** [usnistgov/ACVP-Server#270]
**environment**
Prod

**testSessionId**
n/a

**vsId**
n/a

**Algorithm registration**
n/a

**Endpoint in which the error is experienced**
GET https://acvts.nist.gov:443/health

**Expected behavior**
Expecting a "status" value from the /health endpoint as specified here: https://github.com/usnistgov/ACVP-Server/wiki/Health-Check---Server-Version-Endpoint

**Additional context**
This was working sometime last week. Now getting the following:

{
  "serverVersion": "v1.1.0.28-2",
  "details": [
    {
      "key": "testSessionProcessing",
      "description": "The TestSession internal processing load status.",
      "data": {
        "healthStatusDefinitions": {
          "Healthy": "Oldest pending TestSession is < 1 hours old.",
          "Degraded": "Oldest pending TestSession is > 1 hours old.",
          "Unhealthy": "Oldest pending TestSession is > 4 hours old."
        }
      }
    }
  ]
}

You can see the status value is missing

**Comment by livebe01** [comment]
Hi @mikeboulet,

I queried the /health endpoint after seeing this ticket and the status value came back for me. Early last week (Monday and Tuesday), we experienced an issue where one of ACVTS Prod's internal processes became unresponsive. I believe the behavior you experienced is related to that. I believe the /health endpoint was dependent in some fashion on that process and when it went unresponsive that caused the status value to be omitted. I'll make a note in our internal issue tracking system so that we can track this and look into improving the robustness of the endpoint.

Thanks,

Ben

**Comment by abkarcher** [comment]
Hi @livebe01, it looks likes this has been happening again today; have there been any service outages on the server end or is this just a hiccup on the health endpoint? (We are getting retry messages just fine for a bit now, just wanted to bring it up in case something silently failed!)

Thanks for your time,
Andrew

**Comment by livebe01** [comment]
Hi @abkarcher, thanks for the update. It looks like we were experiencing an issue on 7/6, but it should be resolved I believe.
