### ISSUE TITLE
"error": "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#294]
**environment**
Prod

**testSessionId**
26016

**vsId**
294554

**Expected behavior**
Receive a test vector instead of the message: "error": "Object reference not set to an instance of an object."

**Comment by jbrock24** [comment]
Hi @GlennUL, this is related to issue https://github.com/usnistgov/ACVP/issues/1399 - the fix for this is due out hopefully by the end of this week or early next week to Demo, it will be available on Prod a short time after verifying it's working correctly. Apologies for any inconvenience. Won't it's released, I'll update here.

**Comment by jbrock24** [comment]
Hi @GlennUL, it appears the issue is your fixedInfoPattern, `"fixedInfoPattern":"uPartyInfo||vPartyInfo||t||l"`, is set with a t, which isn't valid. Please refer to https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-hkdf.txt, section `7.3.1.  FixedInfoPatternConstruction` for valid settings. I will look into updating the error message and where it's caught. Thanks for bringing this issue to our attention!

**Comment by GlennUL** [comment]
Hi @jbrock24 Thanks for the info. I removed the t and everything went through successfully.

**Comment by jbrock24** [comment]
Quick head's up, double checked the current version on Dev and it's relaying the correct error. Sorry again, the fix will go out with .32 hopefully by the end of this week, but maybe into the early part of next. I'll reply here when it's published for use and close this issue.

**Comment by jbrock24** [comment]
Also, `t` was supported but it was removed.
