### ISSUE TITLE
KAS-FFC Sp800-56Ar3 dhHybrid1 KdfKc DKM computation

### ISSUE THREAD

**Issue by DavidSedacca** [usnistgov/ACVP-Server#30]
**environment**
Demo

**testSessionId**
122528

**vsId**
364227

**Algorithm registration**
{
    "prereqVals":[
        {
            "algorithm":"DRBG",
            "valValue":"same"
        },
        {
            "algorithm":"HMAC",
            "valValue":"same"
        },
        {
            "algorithm":"SHA",
            "valValue":"same"
        },
        {
            "algorithm":"SafePrimes",
            "valValue":"same"
        }
    ],
    "revision":"Sp800-56Ar3",
    "algorithm":"KAS-FFC",
    "function":[
        "keyPairGen",
        "fullVal"
    ],
    "iutId":"D1E9DE6D343E266A",
    "scheme":{
        "dhHybrid1":{
            "kasRole":[
                "initiator",
                "responder"
            ],
            "kdfMethods":{
                "oneStepKdf":{
                    "auxFunctions":[
                        {
                            "auxFunctionName":"SHA2-512"
                        }
                    ],
                    "fixedInfoPattern":"uPartyInfo||vPartyInfo",
                    "encoding":[
                        "concatenation"
                    ]
                }
            },
            "keyConfirmationMethod":{
                "macMethods":{
                    "HMAC-SHA2-256":{
                        "keyLen":160,
                        "macLen":256
                    }
                },
                "keyConfirmationDirections":[
                    "bilateral"
                ],
                "keyConfirmationRoles":[
                    "provider",
                    "recipient"
                ]
            },
            "l":512
        }
    },
    "domainParameterGenerationMethods":[
        "MODP-4096"
    ]
}

**Endpoint in which the error is experienced**
GET /acvp/v1/testSessions/122528/vectorSets/364227 HTTP/1.1

**Expected behavior**
I expected DKM computation for this "KdfKc" situation to be like what was done for tsId 124356 / vsId 371044, where the capabilities were "KdfNoKc". Instead, DKM shown for the "KdfKc" situation has shorter length (perhaps by the amount used for MAC key) and the visible hex characters are not a substring of the IUT's recomputed DKM value.

**Additional context**
Algorithm registration for tsId 124356 / vsId 371044 KdfNoKc with DKM that matched my expectations:
{
  "prereqVals":[
    {
      "algorithm":"DRBG",
      "valValue":"same"
    },
    {
      "algorithm":"SHA",
      "valValue":"same"
    },
    {
      "algorithm":"SafePrimes",
      "valValue":"same"
    }
  ],
  "revision":"Sp800-56Ar3",
  "algorithm":"KAS-FFC",
  "function":[
    "keyPairGen",
    "fullVal"
  ],
  "iutId":"D1E9DE6D343E266A",
  "scheme":{
    "dhHybrid1":{
      "kasRole":[
        "initiator",
        "responder"
      ],
      "kdfMethods":{
        "oneStepKdf":{
          "auxFunctions":[
            {
              "auxFunctionName":"SHA2-512"
            }
          ],
          "fixedInfoPattern":"uPartyInfo||vPartyInfo",
          "encoding":[
            "concatenation"
          ]
        }
      },
      "l":512
    }
  },
  "domainParameterGenerationMethods":[
    "MODP-4096"
  ]
}

**Comment by DavidSedacca** [comment]
Expanding on "Additional context", attached are JSON files for dhHybrid1 with and without key confirmation. The dkm values in these two situations don't seem to be computed the same way.
[364227_dhHybrid1_KdfKc_capabilities_request_from_IUT.json.txt](https://github.com/usnistgov/ACVP-Server/files/5495243/364227_dhHybrid1_KdfKc_capabilities_request_from_IUT.json.txt)
[364227_dhHybrid1_KdfKc_sample_answers_from_server.json.txt](https://github.com/usnistgov/ACVP-Server/files/5495246/364227_dhHybrid1_KdfKc_sample_answers_from_server.json.txt)
[364227_dhHybrid1_KdfKc_testvectors_from_server.json.txt](https://github.com/usnistgov/ACVP-Server/files/5495248/364227_dhHybrid1_KdfKc_testvectors_from_server.json.txt)
[371044_dhHybrid1_KdfNoKc_capabilities_request_from_IUT.json.txt](https://github.com/usnistgov/ACVP-Server/files/5495249/371044_dhHybrid1_KdfNoKc_capabilities_request_from_IUT.json.txt)
[371044_dhHybrid1_KdfNoKc_example_answers_from_server.json.txt](https://github.com/usnistgov/ACVP-Server/files/5495251/371044_dhHybrid1_KdfNoKc_example_answers_from_server.json.txt)
[371044_dhHybrid1_KdfNoKc_testvectors_from_server.json.txt](https://github.com/usnistgov/ACVP-Server/files/5495253/371044_dhHybrid1_KdfNoKc_testvectors_from_server.json.txt)

**Comment by Kritner** [comment]
It's been a few months since I put together the testing for these algorithms so I was trying to review [SP800-56Ar3](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf) to understand the reasoning behind one of the decision I made.

Reviewing the document again, I might need to put in a modification to testing on our side.

The Key Confirmation testing *currently* is chopping off the DKM bits that are used as a part of the Key Confirmation process from the DKM, but rereading the specification it seems like that was perhaps in error:

![image](https://user-images.githubusercontent.com/8814983/98282157-c7dc5700-1f6b-11eb-8dec-9dcc64636fac.png)
![image](https://user-images.githubusercontent.com/8814983/98282266-f65a3200-1f6b-11eb-9de4-58ee735f5aac.png)

I was originally taking the above as "DerivedKeyingMaterial" only encompasses "KeyData" after "MacKey" is taken from the beginning of it, but reading it again I don't think that is correct.  

So for the above KC tests, "DKM' was only the "KeyData" portion of the original DKM (so the MacKey taken out).  It seems this probably shouldn't be the case.

I would still *guess* that the intention is:

* When not performing key confirmation, the entirety of `dkm` is useable
* When performing key confirmation, only the `KeyData` portion of `dkm` is useable.   Even if this were the case, that does not change the actual bits that make up the entirety of `dkm`.

**Comment by DavidSedacca** [comment]
I agree with the expectation that the actual bits that make up the entirety of dkm should be unaffected by our use of some of those bits for MacKey and others for KeyData. I have attached a text file where I show the hex values for counter, Ze, Zs, iutId, ephemeralPublicIut, serverId, ephemeralPublicServer, and their concatenation "x", and the result of DKM = H(x). I can match the DKM for vsId 371044 KdfNoKc, but my DKM computation doesn't have a substring that matches the VAL case in vsId 364227.
[364227_vs_371044_dkm_computations.txt](https://github.com/usnistgov/ACVP-Server/files/5497913/364227_vs_371044_dkm_computations.txt)

**Comment by Kritner** [comment]
This is pretty strange, i've not yet had luck reproducing the issue your posted about above, and I'm able to confirm our side agree on your results when plugging them directly into the crypto.  I'm not sure if something could have been inadvertently fixed with the change to the removal of MacKey from the DKM or not.

Once we get the change out to demo can we give it another go? (note will need a new vector set created)

**Comment by DavidSedacca** [comment]
I can request fresh vector sets when the change is on the demo server. What is the best way to learn that the change is online? A message in this thread? Or would it show up on https://github.com/usnistgov/ACVP-Server/releases?

**Comment by Kritner** [comment]
it will be in the release notes for a "pre-release", but I also try to update all issues that apply to a release stating that it's on [x] environment

**Comment by Kritner** [comment]
This change will be on demo from release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14) after the scheduled maintenance.

**Comment by Kritner** [comment]
Hey @DavidSedacca just wanted to check in to see if you've had a chance to confirm this change, and if we're still in disagreement over some of the tests

**Comment by DavidSedacca** [comment]
The AFT results from the demo server v1.1.0.14 always indicate to us "result": "failed", "reason": "MacKey does not match; MacData does not match". The VAL test vectors from the demo server v1.1.0.14 now match our expectations, and the server returns "passed for our VAL responses.
An example session:
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/126736/vectorSets/380490/results

**Comment by Kritner** [comment]
Hmm... that's interesting.  I actually noticed that issue and got a fix out for it right around the time that vector set was generated.  Could you try it again? I believe I took care of that issue everywhere and it should be on demo, but I don't have a client that can validate the fix is out there since it only occurs on "non sample" vector sets.

**Comment by DavidSedacca** [comment]
We will check with a fresh test session.

**Comment by DavidSedacca** [comment]
All is good for today's tsId 127591 and vsId 384656, so I think this issue can be closed.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)
