### ISSUE TITLE
DRBG vector sets General exception

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#31]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/124122

**vsId**
/acvp/v1/testSessions/124122/vectorSets/370342

We got below error when trying to fetch vector sets.

> "error": "General exception. Contact service provider."

**Comment by Kritner** [comment]
Hey @AndrewHYang I'll be putting in a correction to the specification for DRBG.  Though the algorithm itself can test up through those lengths of values, we are restricting the values for testing to something smaller.

I'm quite surprised we haven't actually had an issue about this prior to now, but the new planned max rather than 2^35 will be 2,147,483,640.  I'll put in a correction to the specification

**Comment by Kritner** [comment]
This change will be on demo from release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14) after the scheduled maintenance.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)
