### ISSUE TITLE
SHA LDT

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#314]
**environment**
Demo

**testSessionId**
490087

**vsId**
2184938

**Algorithm registration**
{
            "messageLength": [
                256,
                {
                    "min": 8,
                    "max": 65536,
                    "increment": 8
                }
            ],
            "performLargeDataTest": [
                1
            ],
            "algorithm": "SHA2-256",
            "revision": "1.0"
        }

**Additional context**
We have a vendor who is trying to do the SHA Large Data Test and is encountering an issue with it. They believe the "fullLength" value in the vector is set to bytes and not bits. When they test the vector they are able to get the correct result when processing as bytes but when run as bits the results don't match the expected result. Can you confirm if there is an issue in generation or if it's something the vendor needs to look further in to? Thank you.

**Comment by jbrock24** [comment]
So for this calculation we use the [bits in a GiB](https://github.com/usnistgov/ACVP-Server/blob/a4636bcb9d7e70b3e857f537cc13bf7554eee2ee/gen-val/src/generation/src/NIST.CVP.ACVTS.Libraries.Generation/SHA2/v1_0/TestCaseGeneratorLdt.cs#L19) to determine the number of [iterations](https://github.com/usnistgov/ACVP-Server/blob/a4636bcb9d7e70b3e857f537cc13bf7554eee2ee/gen-val/src/crypto/src/NIST.CVP.ACVTS.Libraries.Crypto/SHA/NativeFastSha/NativeFastSha2_256.cs#L77).

Are they calculating bits in GiB instead of GB? This is discussed in the [documentation](https://pages.nist.gov/ACVP/draft-celi-acvp-sha.txt). The [LargeBitString](https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/src/common/src/NIST.CVP.ACVTS.Libraries.Math/LargeBitString/LargeBitString.cs) class used to pass around for all this. ContentLength and FullLength are used throughout, these are all in bits.

**Comment by GlennUL** [comment]
Thanks for the info Joel. I have passed this along.
