### ISSUE TITLE
RSA vector sets are different when isSample is changed.

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#42]
**environment**
Demo

**testSessionId**
127649 & 127655

**vsId**
\testSessions\127649\vectorSets\384961
\testSessions\127655\vectorSets\385004

One of them isSample is true while the other is false.
And when the isSample is false, parameters are missing from the test cases but "deferred": true

**Comment by Kritner** [comment]
@AndrewHYang this is likely due to the fact that if `!infoGeneratedByServer` and not `!isSample`, the onus is on the IUT to generate keys and the "seed" values used to generate them.  When `sample`, we pretty much need to generate everything up front, as to have valid response files for you to download for posting as "your answers", regardless of the value of `infoGeneratedByServer`.

I don't have access to the registrations from the above test sessions, but if you have some example registrations between the two this can be confirmed, if the above explanation does not give enough information.

Thanks for your patience on this, let me know if there's anything else.
