### ISSUE TITLE
KTS IFC Generation Issue

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#54]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/133081

**vsId**
/acvp/v1/testSessions/133081/vectorSets/412213

When generating vectors for KTS-IFC using Modulo Sizes 2048, 3072 and 4096 the vector only includes testing for sizes 2048 and 3072.

**Comment by AndrewHYang** [comment]
Hi @Kritner, may I ask if there is any update of this issue?

**Comment by Kritner** [comment]
Yeah I'm working on something for the various Kas group woes, it's a fairly
significant logic change in group generation for all of Kas 800-56ar3 and
800-56br2. it's a bit slow going trying to find the right balance of using
all the props registered without doing a full Cartesian product, as that
makes the files entirely too large with a significant enough registration.

These changes will not have any impact on the clients, but I am still
working on the change.

**Comment by Kritner** [comment]
A change to group level generation around KAS has been pushed to demo for the [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15) release.

This change is to use all (rather than a subset) of the registered properties within a registration, without doing a cartesian product of the capabilities.

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15)
