### ISSUE TITLE
Possible Shortcoming in ACVP Spec for KAS KDF OneStep

### ISSUE THREAD

**Issue by powersmc** [usnistgov/ACVP-Server#68]
**environment**
Demo (but it presumably affects Prod as well)

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
When you test KAS KDF, the specification designates that 'l' must be provided as a singular value:
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-onestep.html#name-kdf-parameter-json-schema
The specific example provide is l:2048

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions POST

**Expected behavior**
In some cases, we have vendors that support a large array of lengths for their KDFs (specifically with regards to the Derived Key Length).  An example would be a KAS-KDF (OneStep) implementation that provides a generic KDF function where the caller can designate a variable bit length for the output anywhere from 128-4096 (increment by 8).  In order to get full coverage, one would expect that the registration might include a "domain" for the parameter named "l", but rather it is just an integer value in the spec (linked above).  As it is now, it seems that one would need to create a potentially massive array (400+ entries) of KAS-KDF objects, one for each "l" value supported, in order to get full coverage.

**Additional context**
N/A

**Comment by Kritner** [comment]
The intention was for the `l` value to be more of a "largest value supported by the IUT".  My thinking was due to there being no logic differences between "2 loops through the KDF" and "10 loops through", there wasn't much to gain by testing against a multitude of `l` values.  

This could obviously be re-evaluated, but would likely come under a separate testing revision since we've already had validations against this revision.

**Comment by powersmc** [comment]
Sounds good to me.  We will run with the assumption for now that we should just test with the maximum 'l' value.
