### ISSUE TITLE
KTS-IFC Unexpected Behavior

### ISSUE THREAD

**Issue by powersmc** [usnistgov/ACVP-Server#69]
**environment**
Demo

**testSessionId**
138218

**vsId**
433495

**Algorithm registration**
{
        "algorithm":"KTS-IFC",
        "revision":"Sp800-56Br2",
        "function":[
          "keyPairGen",
          "partialVal"
        ],
        "iutId":"[REMOVED]"
        "keyGenerationMethods":[
          "rsakpg1-crt",
          "rsakpg2-crt"
        ],
        "modulo":[
          2048,
          3072,
          4096,
          6144,
          8192
        ],
		"fixedPubExp":"010001",
        "scheme":{
          "KTS-OAEP-basic":{
            "kasRole":[
              "initiator",
              "responder"
            ],
            "ktsMethod":{
              "hashAlgs":[
                "SHA2-224",
                "SHA2-256",
                "SHA2-384",
                "SHA2-512",
                "SHA3-224",
                "SHA3-256",
                "SHA3-384",
                "SHA3-512"
              ],
              "supportsNullAssociatedData":true,
              "associatedDataPattern":"uPartyInfo||vPartyInfo",
              "encoding":[
                "concatenation"
              ]
            },
            "l":1024
          }
        }
      }

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/138218/vectorSets/433495

**Expected behavior**
The registration for this test session and vector set succeeded and the server proceeded to generate vectors.  It was observed, however, upon downloading the vectors that the specific vector set noted above did not actually contain any vectors but rather just contained the contents:
[{'acvVersion': '1.0'}, {'error': 'KLen length too large.'}]

It's unclear what is meant by this error.  If this refers to the modulo value, then the spec here seems to indicate that values up to 8192 are acceptable:
https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#modulo

**Additional context**

**Comment by powersmc** [comment]
Just as a follow-up to this query, after some further experimentation I found that the issue seems to reside in the "l":1024 parameter.  If I lower this value to 256, I can get vectors to generate just fine.

I note that based on the spec here: https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-ifc.html#table-4 that it seems to indicate that 1024 is an acceptable value, so this might just be an issue with the spec not matching what the server is actually enforcing.

**Comment by Kritner** [comment]
Sorry for the delay, I'll be trying to take a look at this sometime soon

**Comment by Kritner** [comment]
An update for this has been pushed to demo.  The issue was with taking in an `l` value that was "all encompassing" to all registered modulo sizes, that length of `l` isn't valid.  

![image](https://user-images.githubusercontent.com/8814983/106880580-88c4bb80-66aa-11eb-9b26-1653b1fdc55e.png)

`nLen - (2 * Hlen) - 2` would be the maximum value a `kLen` can support for a given modulo and hash function, so for mod 2048 with a hash function of sha2-512 you would have:

`nLen - (2 * HLen) - 2` -> `(2048 / 8) - (2 *  (512 / 8)) - 2` -> `256 - (2 * 64) - 2` -> `256 - 128 - 2` -> `126`
126 bytes to bits -> 1008.  The registered `l` value of 1024 exceeds the 1008, so was throwing the "invalid kLen" from our side.

This is not on you, just writing out my discovery process and how I went about fixing it.

Now, rather than *always* using the registered `l` value, I'll use the `Min(l, maxSupportedForModAndHashFunction)` for each group of modulo and hash.

Hopefully that makes sense!

**Comment by powersmc** [comment]
Thanks for the detailed explanation & quick turnaround!

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15)
