### ISSUE TITLE
KAS-ECC Component mode noKdfNoKc option inappropriately requires hashAlg

### ISSUE THREAD

**Issue by swkeypair** [usnistgov/ACVP-Server#7]
The KAS ECC testing for the Component mode, noKdfnoKc scenario requires the shared secret Z of SP 800-56Ar3 Section 5.7.1.2 (for ECC) or 5.7.1.1 (for FFC) to be hashed. It appears this is only for the purpose of testing, carrying over the practice described in the CAVS [kasvs.pdf](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/keymgmt/KASVS.pdf).

Why is hashAlg required for the noKdfNoKc case?

This practice is not explained well in the test specification and so will result in confusion. It also seems inconsistent with other testing methods that don't impose extraneous primitives for test purposes.
 
**Scenario**: [Mode: _Component_; option: _noKdfNoKc_
](https://usnistgov.github.io/ACVP/draft-fussell-acvp-kas-ecc.html#name-kas-ecc-scheme-capabilities)

The [relevant KAS ECC specification section 7.7.2](https://usnistgov.github.io/ACVP/draft-fussell-acvp-kas-ecc.html#name-kas-ecc-parameter-set-detai) _**requires**_ the selection of a hashAlg:

> "noKdfNoKc" REQUIRES "hashAlg"

The 3rd bullet of [Section 6.2.1 KAS-ECC Requirements Covered](https://usnistgov.github.io/ACVP/draft-fussell-acvp-kas-ecc.html#name-kas-ecc-requirements-covere) appears to be inconsistent - the _NoKc_ part of _noKdfNoKc_ means no key confirmation:

> SP 800-56a - 5.1 Cryptographic Hash Functions. All modes of performing KAS SHALL make use of a hash function. 
> The hash function **MAY** be used for confirmation of a successfully generated shared secret Z (_noKdfNoKc_), 
> or as a primitive within the KDF being tested (kdfNoKc and kdfKc). 

When there is no KDF and no key confirmation (the _noKdfNoKc_ scenario), the hash is not used by the implementation under test. The practice of hashing Z for test purposes seems to derive from the CAVS testing described in [KASVS.pdf Section 2 final paragraph](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/keymgmt/KASVS.pdf#page=6):

> Note that the validation testing without key confirmation asks for a MAC algorithm to perform the testing. 
> It is not a prerequisite to getting the IUT validated. Likewise, if “all of SP800-56A except the key derivation function” 
> is being tested, the testing requires the shared secret value ZZ to be hashed. 
> The hash function is only used to perform the test and is not a prerequisite to getting the IUT validated.

**Comment by Kritner** [comment]
FWIW, some of this is addressed in the KAS-SSC-* style testing, where the hash function for shared secret computation is **optional**.  I would strongly recommend moving to the more up to date KAS testing if at all possible - this issue is addressed, the registrations are a bit simpler, and it's targeting a more up to date standard.

All that being said, yes, the 1.0 revision testing against KAS was to get as close to the CAVS style testing as possible.  The required hashing of the `z` value for shared secret computation always bothered me as well, but CAVS was doing it, so our initial translation of that testing was doing it as well.

In the newer testing that targets SP800-56Ar3, the SSC style testing is introduced, where the hashing of `z` is optional.  

> This practice is not explained well in the test specification and so will result in confusion. It also seems inconsistent with other testing methods that don't impose extraneous primitives for test purposes.

If I were to guess, it would probably have something to do with the `z` value should not be exported from the crypto module in the clear (as per the SP800-56A* IIRC). The "hashing" of `z` prior to export satisfied some of that wording from the specification.  

> The 3rd bullet of Section 6.2.1 KAS-ECC Requirements Covered appears to be inconsistent - the NoKc part of noKdfNoKc means no key confirmation:
> 
>> SP 800-56a - 5.1 Cryptographic Hash Functions. All modes of performing KAS SHALL make use of a hash function.
The hash function MAY be used for confirmation of a successfully generated shared secret Z (noKdfNoKc),
or as a primitive within the KDF being tested (kdfNoKc and kdfKc).
> 
> When there is no KDF and no key confirmation (the noKdfNoKc scenario), the hash is not used by the implementation under test. The practice of hashing Z for test purposes seems to derive from the CAVS testing described in KASVS.pdf Section 2 final paragraph:
> 
> Note that the validation testing without key confirmation asks for a MAC algorithm to perform the testing.
It is not a prerequisite to getting the IUT validated. Likewise, if “all of SP800-56A except the key derivation function”
is being tested, the testing requires the shared secret value ZZ to be hashed.
The hash function is only used to perform the test and is not a prerequisite to getting the IUT validated.

I'm not sure I understand the concern with the sections in the specification.  Is it the use of *MAY* rather than *SHALL*? Specifically around the fact that we're introducing things outside of the scope of the module to achieve testing?  Something else?  Either way, I probably agree; the testing using a hash or mac where it was not required for the crypto itself is a bit strange.  Though some of it is conceivably covered by the SP800-56A* document itself regarding management of secret values.

If you have a specific suggestion to the document, feel free to put in a PR for it, or we can discuss more here as well.

**Comment by swkeypair** [comment]
Thank you for responding.

> FWIW, some of this is addressed in the KAS-SSC-* style testing, where the hash function for shared secret computation 
> is optional. I would strongly recommend moving to the more up to date KAS testing if at all possible - 
> this issue is addressed, the registrations are a bit simpler, and it's targeting a more up to date standard.
We will review the guidances again for IG D-1rev3, IG D.2 and IG D.9, and likely will pursue KAS-SSC as suggested. 

> In the newer testing that targets SP800-56Ar3, the SSC style testing is introduced, where the hashing of z is optional.
Please note that the [ACVP KAS ECC JSON Specification](https://usnistgov.github.io/ACVP/draft-fussell-acvp-kas-ecc.html) (the older style testing) _does_ cite conformance to SP 800-56Ar3 - in Section 6.2:

> The tests described in this document have the intention of ensuring an implementation is conformant to [SP800-56a].
and following this link to the cited specification in Section 14:

> [SP800-56a]
> Barker, E., Chen, L., Roginsky, A., Vassilev, A., and R. Davis, "SP800-56Ar3 Recommendation for Pair-Wise 
> Key-Establishment Schemes Using Discrete Logarithm Cryptography", 2018, 
> <[https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf)>.

> I'm not sure I understand the concern with the sections in the specification. Is it the use of MAY rather than SHALL?
The statement refers to the use of key confirmation when _noKdfNoKc_ is specifically _not_ using key confirmation.

**Comment by Kritner** [comment]
> Please note that the ACVP KAS ECC JSON Specification (the older style testing) does cite conformance to SP 800-56Ar3 - in Section 6.2:

>> The tests described in this document have the intention of ensuring an implementation is conformant to [SP800-56a].

Ah, correct, the document should probably cite an earlier version of the standard, which will require updating of section numbers from the requirements covered/not covered sections as well.

-----

> The statement refers to the use of key confirmation when noKdfNoKc is specifically not using key confirmation.

I still don't follow, you're referring to this sentence, correct?

https://usnistgov.github.io/ACVP/draft-fussell-acvp-kas-ecc.html#section-6.2.1-1.3.1

> SP 800-56a - 5.1 Cryptographic Hash Functions. All modes of performing KAS SHALL make use of a hash function.
The hash function MAY be used for confirmation of a successfully generated shared secret Z (noKdfNoKc),
or as a primitive within the KDF being tested (kdfNoKc and kdfKc).

is it the word "confirmation" in "MAY be used for ***confirmation*** of a successfully generated shared secret Z (noKdfNoKc)"?  Would "validation" be a better word, as to not confuse it with the "Key Confirmation" process?

**Comment by swkeypair** [comment]
> is it the word "confirmation" in "MAY be used for confirmation of a successfully generated shared secret Z (noKdfNoKc)"? Would "validation" be a better word, as to not confuse it with the "Key Confirmation" process?

This is the right context of the question. As I understand this statement, _"MAY be used for confirmation of a successfully generated shared secret Z (noKdfNoKc)"_ is intended to refer to the 56Ar3 general option to address Key Confirmation, not that it _may_ be used in the test. In the context of key confirmation, NoKdfNoKc means key confirmation is _not_used. 

I very much appreciate your interaction, it has helped to clarify the current status and context. I have put related questions to Tim Hall as an outcome of the Sept 23 ICMC session on CAVP. The reality that the current KAS is not usable for 56Ar3 seems to mean this question is moot. We hope Tim can answer questions about the correct scope of testing to match FIPS 140-2 IGs for scenarios that involve industry standard protocols (e.g. SP 800-135, TLS et al).

**Comment by Kritner** [comment]
I've made several updates to the varying kas specifications (but mostly around the 1.0 revision of testing).  Hopefully these updates address all the concerns between this issue and our email correspondence; but if I've missed something let me know.

**Comment by swkeypair** [comment]
Looks good; thank you.
