### ISSUE TITLE
EDDSA SigGen sending invalid test cases

### ISSUE THREAD

**Issue by mikebusa** [usnistgov/ACVP-Server#79]
**environment**
Demo

**testSessionId**
163710

**vsId**
486011

**Algorithm registration**
[
  {
    "acvVersion":"1.0"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "algorithm":"EDDSA",
        "mode":"sigGen",
        "revision":"1.0",
        "curve":[
          "ED-25519",
          "ED-448"
        ],
        "pure":true,
        "preHash":false,
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ]
      }
    ]
  }
]

**Expected behavior**
When preHash is set to false, no test cases with the "context" parameters are supposed to be received. TCIDs 11-20 as well as TCIDs 1045-2068 have both preHash=false and a context parameter, and it is causing the test cases to fail verification. They always belong to test groups with a curve = ED-448.

**Comment by Kritner** [comment]
@mikebusa can you confirm with a new vector set that this is still occurring? I tried running my own and didn't see the behavior you were describing.  The vector set from the original issue has since expired out, so I don't have access to the generated files.

I'm not super familiar with this algorithm but looking over [FIPS 186-5](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf) - a `context` *can* exist for `prehash` for either curve, but for `no prehash`, a context can only exist for the `ED-448` curve, is that correct?
